/**
 * ServiceFlow System Constants & Enums
 */

const ROLES = Object.freeze({
  EMPLOYEE: 'EMPLOYEE',
  SUPPORT_AGENT: 'SUPPORT_AGENT',
  ADMIN: 'ADMIN'
});

const TICKET_STATUSES = Object.freeze({
  OPEN: 'Open',
  IN_PROGRESS: 'In Progress',
  ON_HOLD: 'On Hold',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed'
});

const TICKET_PRIORITIES = Object.freeze({
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical'
});

const TICKET_CATEGORIES = Object.freeze({
  HARDWARE: 'Hardware',
  SOFTWARE: 'Software',
  NETWORK: 'Network',
  ACCESS_LOGIN: 'Access/Login',
  EMAIL: 'Email',
  OTHER: 'Other'
});

// SLA duration in hours mapped to priority
const SLA_HOURS = Object.freeze({
  Critical: 4,
  High: 8,
  Medium: 24,
  Low: 72
});

const AUDIT_ACTIONS = Object.freeze({
  TICKET_CREATED: 'TICKET_CREATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_REASSIGNED: 'TICKET_REASSIGNED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  RESOLUTION_ADDED: 'RESOLUTION_ADDED',
  TICKET_RESOLVED: 'TICKET_RESOLVED',
  TICKET_CLOSED: 'TICKET_CLOSED',
  TICKET_REOPENED: 'TICKET_REOPENED'
});

const NOTIFICATION_TYPES = Object.freeze({
  ASSIGNMENT: 'ASSIGNMENT',
  STATUS_CHANGE: 'STATUS_CHANGE',
  NEW_COMMENT: 'NEW_COMMENT',
  RESOLUTION: 'RESOLUTION',
  PRIORITY_CHANGE: 'PRIORITY_CHANGE',
  SYSTEM: 'SYSTEM'
});

// Allowed status transitions mapping
const VALID_STATUS_TRANSITIONS = Object.freeze({
  [TICKET_STATUSES.OPEN]: [TICKET_STATUSES.IN_PROGRESS],
  [TICKET_STATUSES.IN_PROGRESS]: [TICKET_STATUSES.ON_HOLD, TICKET_STATUSES.RESOLVED],
  [TICKET_STATUSES.ON_HOLD]: [TICKET_STATUSES.IN_PROGRESS],
  [TICKET_STATUSES.RESOLVED]: [TICKET_STATUSES.CLOSED, TICKET_STATUSES.IN_PROGRESS],
  [TICKET_STATUSES.CLOSED]: [TICKET_STATUSES.IN_PROGRESS] // Re-opened by Admin
});

module.exports = {
  ROLES,
  TICKET_STATUSES,
  TICKET_PRIORITIES,
  TICKET_CATEGORIES,
  SLA_HOURS,
  AUDIT_ACTIONS,
  NOTIFICATION_TYPES,
  VALID_STATUS_TRANSITIONS
};
